### PR TITLE
use custom polyfill

### PR DESCRIPTION
**Pull request by josex2r**
Use local polyfill to replace `const` by `var`.

### CODE REVIEW

**Comment by kcmr** [comment]
This doesn't work. polyfills should be loaded before the import. Anyway, moving vendors before the import does not work. Check out the generated dist inside the addon.

- Add `buildForProduction: { enabled: true }` in `ember-cli-build.js`
- Run `ember build --env production`

**Comment by josex2r** [comment]
It works, but Babel changes some var names. That's why you are not seeing the same version of the polyfill.

**Comment by kcmr** [comment]
> It works, but the minifier changes some var names. That's why you are not seeing the same version of the polyfill.

No, it doesn't work. Try the demo.

**Pull request merged**
